package JavaFiles;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.Enumeration;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

public class Editor extends javax.swing.JDialog {

     /*Representación por medio de clave de los contadores
     public int MPrimerVez[]={MPVm1A,MPV1A,MPV2a4A,MPV5a9A,MPV10a14A,MPV15a19A,MPV20a29A,MPV30a49A,MPV50a59A,MPV60yMas};
     public int HPrimerVez[]={HPVm1A,HPV1A,HPV2a4A,HPV5a9A,HPV10a14A,HPV15a19A,HPV20a29A,HPV30a49A,HPV50a59A,HPV60yMas};
     public int MSubSecuente[]={MSsm1A,MSs1A,MSs2a4A,MSs5a9A,MSs10a14A,MSs15a19A,MSs20a29A,MSs30a49A,MSs50a59A,MSs60yMas};
     public int HSubSecuente[]={HSsm1A,HSs1A,HSs2a4A,HSs5a9A,HSs10a14A,HSs15a19A,HSs20a29A,HSs30a49A,HSs50a59A,HSs60yMas};
     public int MSeguroPopular[]={Mm1ASP,M1ASP,M2a4ASP,M5a9ASP,M10a14ASP,M15a19ASP,M20a29ASP,M30a49ASP,M50a59ASP,M60yMasSP};
     public int HSeguroPopular[]={Hm1ASP,H1ASP,H2a4ASP,H5a9ASP,H10a14ASP,H15a19ASP,H20a29ASP,H30a49ASP,H50a59ASP,H60yMasSP};
     public int MProspera[]={Mm1AP,M1AP,M2a4AP,M5a9AP,M10a14AP,M15a19AP,M20a29AP,M30a49AP,M50a59AP,M60yMasP};
     public int HProspera[]={Hm1AP,H1AP,H2a4AP,H5a9AP,H10a14AP,H15a19AP,H20a29AP,H30a49AP,H50a59AP,H60yMasP};
     public int MPorAño[]={PVAm1A,PVA1A,PVA2a4A,PVA5a9A,PVA10a14A,PVA15a19A,PVA20a29A,PVA30a49A,PVA50a59A,PVA60yMas};
     public int HPorAño[]={PVAm1A,PVA1A,PVA2a4A,PVA5a9A,PVA10a14A,PVA15a19A,PVA20a29A,PVA30a49A,PVA50a59A,PVA60yMas};*/

    public int MPrimerVez[] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    public int HPrimerVez[] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    public int MSubSecuente[] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    public int HSubSecuente[] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    public int MSeguroPopular[] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    public int HSeguroPopular[] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    public int PReferidos[] = {0, 0};
    public int PDerHab[] = {0, 0, 0, 0};
    public int PPPrimerVez[] = {0, 0, 0, 0, 0, 0, 0};
    public int PPSubSecuente[] = {0, 0, 0, 0, 0, 0, 0};
    public int SPPrograma[] = {0, 0, 0, 0, 0, 0, 0};
    public int MPorAño[]={0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    public int HPorAño[]={0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    public static String Edades[] = {"< 1 Año", "1 Año", "2-4 Años", "5-9 Años", "10-14 Años", "15-19 Años", "20-29 Años", "30-49 Años", "50-59 Años", "60 y Mas Años"};
    public static String Variables[] = {"Enfermedades Transmisibles", "Crónico Degenerativas", "Otras Enfermedades", "A Sanos", "Planificación Familiar", "Salud Bucal", "Salud Mental"};

    public static int Mujeres, Hombres, Primerizas, Primerizos, MSubsecuentes, HSubsecuentes, MPConSeguroPopular, MSSConSeguroPopular, MConSeguroPopular, HPConSeguroPopular, HSSConSeguroPopular, HConSeguroPopular, ConProspera;
    public static int PPPrimerVezCount, PPSubSecuenteCount, PPSP;
    public static String Sexo, Frec, Edad, Referencia, Program, SeguroP, DerechoHabiencia, PorProg, NoMedicas, Cobertura, Clave;
    public static Sujeto Persona;
    public static int ControlRB, ControlSexo, ControlFreq, ControlProg, ControlAux;
    
    public Editor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GCSexo = new javax.swing.ButtonGroup();
        GCFrecuencia = new javax.swing.ButtonGroup();
        GCEdad = new javax.swing.ButtonGroup();
        GPPVariable = new javax.swing.ButtonGroup();
        GReferencia = new javax.swing.ButtonGroup();
        GProspera = new javax.swing.ButtonGroup();
        GSeguroPopular = new javax.swing.ButtonGroup();
        GDerechoHabiencia = new javax.swing.ButtonGroup();
        GPorAño = new javax.swing.ButtonGroup();
        PanReferencia = new javax.swing.JPanel();
        PacientesReferidos = new javax.swing.JRadioButton();
        PacientesContraReferidos = new javax.swing.JRadioButton();
        NAReferencia = new javax.swing.JRadioButton();
        PanSeguroPopular = new javax.swing.JPanel();
        SeguroPopular = new javax.swing.JRadioButton();
        NASeguroPopular = new javax.swing.JRadioButton();
        PanVariable = new javax.swing.JPanel();
        VEnfermedadesTransmisibles = new javax.swing.JRadioButton();
        VCronicoDegenerativas = new javax.swing.JRadioButton();
        VOtrasEnfermedades = new javax.swing.JRadioButton();
        VASanos = new javax.swing.JRadioButton();
        VPlanificacionFamiliar = new javax.swing.JRadioButton();
        VSaludBucal = new javax.swing.JRadioButton();
        VSaludMental = new javax.swing.JRadioButton();
        NAVariable = new javax.swing.JRadioButton();
        PanPrograma = new javax.swing.JPanel();
        Prospera = new javax.swing.JRadioButton();
        NAProspera = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        Consulta = new javax.swing.JPanel();
        PanSexo = new javax.swing.JPanel();
        SMujer = new javax.swing.JRadioButton();
        SHombre = new javax.swing.JRadioButton();
        PanEdad = new javax.swing.JPanel();
        Em1Año = new javax.swing.JRadioButton();
        E1Año = new javax.swing.JRadioButton();
        E2a4Años = new javax.swing.JRadioButton();
        E5a9Años = new javax.swing.JRadioButton();
        E10a14Años = new javax.swing.JRadioButton();
        E15a19Años = new javax.swing.JRadioButton();
        E20a29Años = new javax.swing.JRadioButton();
        E30a49Años = new javax.swing.JRadioButton();
        E50a59Años = new javax.swing.JRadioButton();
        E60YMasAños = new javax.swing.JRadioButton();
        PanFrecuencia = new javax.swing.JPanel();
        FPrimeraVez = new javax.swing.JRadioButton();
        FSubsecuente = new javax.swing.JRadioButton();
        PanCobertura = new javax.swing.JPanel();
        PrimeraVezEnElAno = new javax.swing.JRadioButton();
        NAPrimeraVezEnElAno = new javax.swing.JRadioButton();
        PanDerechoHabiencia = new javax.swing.JPanel();
        DHIMSS = new javax.swing.JRadioButton();
        DHISSSTE = new javax.swing.JRadioButton();
        DHSMNG = new javax.swing.JRadioButton();
        DHOtras = new javax.swing.JRadioButton();
        NADH = new javax.swing.JRadioButton();
        guardar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setTitle("Editor");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        PanReferencia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Referencia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        GReferencia.add(PacientesReferidos);
        PacientesReferidos.setText("Pacientes Referidos");

        GReferencia.add(PacientesContraReferidos);
        PacientesContraReferidos.setText("Pacientes Contrarreferidos");

        GReferencia.add(NAReferencia);
        NAReferencia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NAReferencia.setText("No Aplica");
        NAReferencia.setToolTipText("");

        javax.swing.GroupLayout PanReferenciaLayout = new javax.swing.GroupLayout(PanReferencia);
        PanReferencia.setLayout(PanReferenciaLayout);
        PanReferenciaLayout.setHorizontalGroup(
            PanReferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanReferenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanReferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PacientesReferidos)
                    .addComponent(PacientesContraReferidos)
                    .addComponent(NAReferencia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanReferenciaLayout.setVerticalGroup(
            PanReferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanReferenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PacientesReferidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PacientesContraReferidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NAReferencia))
        );

        PanSeguroPopular.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seguro Popular", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        GSeguroPopular.add(SeguroPopular);
        SeguroPopular.setText("Seguro Popular");

        GSeguroPopular.add(NASeguroPopular);
        NASeguroPopular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NASeguroPopular.setText("No Aplica");
        NASeguroPopular.setToolTipText("");

        javax.swing.GroupLayout PanSeguroPopularLayout = new javax.swing.GroupLayout(PanSeguroPopular);
        PanSeguroPopular.setLayout(PanSeguroPopularLayout);
        PanSeguroPopularLayout.setHorizontalGroup(
            PanSeguroPopularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanSeguroPopularLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanSeguroPopularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SeguroPopular)
                    .addComponent(NASeguroPopular))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanSeguroPopularLayout.setVerticalGroup(
            PanSeguroPopularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanSeguroPopularLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SeguroPopular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NASeguroPopular))
        );

        PanVariable.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Por Programa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        GPPVariable.add(VEnfermedadesTransmisibles);
        VEnfermedadesTransmisibles.setText("Enfermedades Transmisibles");

        GPPVariable.add(VCronicoDegenerativas);
        VCronicoDegenerativas.setText("Crónico Degenerativas");

        GPPVariable.add(VOtrasEnfermedades);
        VOtrasEnfermedades.setText("Otras Enfermedades");

        GPPVariable.add(VASanos);
        VASanos.setText("A Sanos");

        GPPVariable.add(VPlanificacionFamiliar);
        VPlanificacionFamiliar.setText("Planificación Familiar");

        GPPVariable.add(VSaludBucal);
        VSaludBucal.setText("Salud Bucal");

        GPPVariable.add(VSaludMental);
        VSaludMental.setText("Salud Mental");

        GPPVariable.add(NAVariable);
        NAVariable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NAVariable.setText("No Aplica");
        NAVariable.setToolTipText("");

        javax.swing.GroupLayout PanVariableLayout = new javax.swing.GroupLayout(PanVariable);
        PanVariable.setLayout(PanVariableLayout);
        PanVariableLayout.setHorizontalGroup(
            PanVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanVariableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VEnfermedadesTransmisibles)
                    .addComponent(VCronicoDegenerativas)
                    .addComponent(VOtrasEnfermedades)
                    .addComponent(VASanos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(PanVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VPlanificacionFamiliar)
                    .addComponent(VSaludBucal)
                    .addComponent(VSaludMental)
                    .addComponent(NAVariable)))
        );
        PanVariableLayout.setVerticalGroup(
            PanVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanVariableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VPlanificacionFamiliar)
                    .addComponent(VEnfermedadesTransmisibles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VSaludBucal)
                    .addComponent(VCronicoDegenerativas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VSaludMental)
                    .addComponent(VOtrasEnfermedades))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NAVariable)
                    .addComponent(VASanos)))
        );

        PanPrograma.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Prospera", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        GProspera.add(Prospera);
        Prospera.setText("Prospera");

        GProspera.add(NAProspera);
        NAProspera.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NAProspera.setText("No Aplica");
        NAProspera.setToolTipText("");

        javax.swing.GroupLayout PanProgramaLayout = new javax.swing.GroupLayout(PanPrograma);
        PanPrograma.setLayout(PanProgramaLayout);
        PanProgramaLayout.setHorizontalGroup(
            PanProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanProgramaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NAProspera)
                    .addComponent(Prospera))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        PanProgramaLayout.setVerticalGroup(
            PanProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanProgramaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Prospera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NAProspera))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Infección de transmisión sexual", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jRadioButton1.setText("Infectado");

        jRadioButton2.setText("No infectado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Consulta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consulta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        PanSexo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sexo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        GCSexo.add(SMujer);
        SMujer.setText("Mujer");

        GCSexo.add(SHombre);
        SHombre.setText("Hombre");

        javax.swing.GroupLayout PanSexoLayout = new javax.swing.GroupLayout(PanSexo);
        PanSexo.setLayout(PanSexoLayout);
        PanSexoLayout.setHorizontalGroup(
            PanSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanSexoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SMujer)
                    .addComponent(SHombre))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanSexoLayout.setVerticalGroup(
            PanSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanSexoLayout.createSequentialGroup()
                .addComponent(SMujer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SHombre))
        );

        PanEdad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        GCEdad.add(Em1Año);
        Em1Año.setText("< 1 Año");

        GCEdad.add(E1Año);
        E1Año.setText("1 Año");

        GCEdad.add(E2a4Años);
        E2a4Años.setText("2-4 Años");

        GCEdad.add(E5a9Años);
        E5a9Años.setText("5-9 Años");

        GCEdad.add(E10a14Años);
        E10a14Años.setText("10-14 Años");

        GCEdad.add(E15a19Años);
        E15a19Años.setText("15-19 Años");

        GCEdad.add(E20a29Años);
        E20a29Años.setText("20-29 Años");

        GCEdad.add(E30a49Años);
        E30a49Años.setText("30-49 Años");

        GCEdad.add(E50a59Años);
        E50a59Años.setText("50-59 Años");

        GCEdad.add(E60YMasAños);
        E60YMasAños.setText("60 y Más Años");

        javax.swing.GroupLayout PanEdadLayout = new javax.swing.GroupLayout(PanEdad);
        PanEdad.setLayout(PanEdadLayout);
        PanEdadLayout.setHorizontalGroup(
            PanEdadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanEdadLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanEdadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Em1Año)
                    .addComponent(E1Año)
                    .addComponent(E2a4Años)
                    .addComponent(E5a9Años)
                    .addComponent(E10a14Años))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanEdadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(E15a19Años)
                    .addComponent(E20a29Años)
                    .addComponent(E30a49Años)
                    .addComponent(E50a59Años)
                    .addComponent(E60YMasAños)))
        );
        PanEdadLayout.setVerticalGroup(
            PanEdadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanEdadLayout.createSequentialGroup()
                .addGroup(PanEdadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanEdadLayout.createSequentialGroup()
                        .addComponent(E15a19Años)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(E20a29Años)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(E30a49Años)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(E50a59Años)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(E60YMasAños))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanEdadLayout.createSequentialGroup()
                        .addComponent(Em1Año)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(E1Año)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(E2a4Años)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(E5a9Años)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(E10a14Años)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanFrecuencia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Frecuencia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        GCFrecuencia.add(FPrimeraVez);
        FPrimeraVez.setText("Primera vez");

        GCFrecuencia.add(FSubsecuente);
        FSubsecuente.setText("Subsecuente");

        javax.swing.GroupLayout PanFrecuenciaLayout = new javax.swing.GroupLayout(PanFrecuencia);
        PanFrecuencia.setLayout(PanFrecuenciaLayout);
        PanFrecuenciaLayout.setHorizontalGroup(
            PanFrecuenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanFrecuenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanFrecuenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FPrimeraVez)
                    .addComponent(FSubsecuente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanFrecuenciaLayout.setVerticalGroup(
            PanFrecuenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanFrecuenciaLayout.createSequentialGroup()
                .addComponent(FPrimeraVez, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FSubsecuente))
        );

        PanCobertura.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cobertura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        GPorAño.add(PrimeraVezEnElAno);
        PrimeraVezEnElAno.setText("Primera vez en el año");

        GPorAño.add(NAPrimeraVezEnElAno);
        NAPrimeraVezEnElAno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NAPrimeraVezEnElAno.setText("No Aplica");

        javax.swing.GroupLayout PanCoberturaLayout = new javax.swing.GroupLayout(PanCobertura);
        PanCobertura.setLayout(PanCoberturaLayout);
        PanCoberturaLayout.setHorizontalGroup(
            PanCoberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanCoberturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PrimeraVezEnElAno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NAPrimeraVezEnElAno)
                .addGap(30, 30, 30))
        );
        PanCoberturaLayout.setVerticalGroup(
            PanCoberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanCoberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(PrimeraVezEnElAno)
                .addComponent(NAPrimeraVezEnElAno))
        );

        javax.swing.GroupLayout ConsultaLayout = new javax.swing.GroupLayout(Consulta);
        Consulta.setLayout(ConsultaLayout);
        ConsultaLayout.setHorizontalGroup(
            ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanCobertura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ConsultaLayout.createSequentialGroup()
                        .addGroup(ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PanFrecuencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanSexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ConsultaLayout.setVerticalGroup(
            ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ConsultaLayout.createSequentialGroup()
                        .addComponent(PanSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanCobertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanDerechoHabiencia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Derechohabiencia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        GDerechoHabiencia.add(DHIMSS);
        DHIMSS.setText("IMSS");

        GDerechoHabiencia.add(DHISSSTE);
        DHISSSTE.setText("ISSSTE");

        GDerechoHabiencia.add(DHSMNG);
        DHSMNG.setText("SMNG");

        GDerechoHabiencia.add(DHOtras);
        DHOtras.setText("Otras");

        GDerechoHabiencia.add(NADH);
        NADH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NADH.setText("No Aplica");
        NADH.setToolTipText("");

        javax.swing.GroupLayout PanDerechoHabienciaLayout = new javax.swing.GroupLayout(PanDerechoHabiencia);
        PanDerechoHabiencia.setLayout(PanDerechoHabienciaLayout);
        PanDerechoHabienciaLayout.setHorizontalGroup(
            PanDerechoHabienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanDerechoHabienciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanDerechoHabienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DHSMNG)
                    .addGroup(PanDerechoHabienciaLayout.createSequentialGroup()
                        .addGroup(PanDerechoHabienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DHIMSS)
                            .addComponent(DHISSSTE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanDerechoHabienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NADH)
                            .addComponent(DHOtras))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        PanDerechoHabienciaLayout.setVerticalGroup(
            PanDerechoHabienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanDerechoHabienciaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanDerechoHabienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DHIMSS)
                    .addComponent(DHOtras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanDerechoHabienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DHISSSTE)
                    .addComponent(NADH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DHSMNG))
        );

        guardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        guardar.setText("Guardar");
        guardar.setToolTipText("Guarda los cambios realizados");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        cancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.setToolTipText("Cancela los cambios realizados");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Consulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PanVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanReferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addComponent(PanDerechoHabiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanSeguroPopular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(Consulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PanVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PanReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PanDerechoHabiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PanPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PanSeguroPopular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        Persona = null;
        Sexo = null;
        Frec = null;
        Edad = null;
        Referencia = null;
        Program = null;
        SeguroP = null;
        DerechoHabiencia = null;
        PorProg = null;
        NoMedicas = null;
        Cobertura = null;
        Clave = null;

        LimpiarControles();

        if (SMujer.isSelected()) {
            Sexo = "Mujer";
            Clave = "M";
        } else if (SHombre.isSelected()) {
            Sexo = "Hombre";
            Clave = "H";
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione el \"Sexo\" de la persona");
            ControlRB = 1;
        }
        if (ControlRB == 0) {
            if (FPrimeraVez.isSelected()) {
                Frec = "Primera vez";
                Clave = Clave + "PV";
            } else if (FSubsecuente.isSelected()) {
                Frec = "Subsecuente";
                Clave = Clave + "Ss";
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione la \"Frecuencia\" de asistencia\na la Unidad Médica");
                ControlRB = 1;
            }
            if (ControlRB == 0) {
                if (Em1Año.isSelected()) {
                    Edad = "< 1 Año";
                    Clave = Clave + "m1A";
                } else if (E1Año.isSelected()) {
                    Edad = "1 Año";
                    Clave = Clave + "1A";
                } else if (E2a4Años.isSelected()) {
                    Edad = "2-4 Años";
                    Clave = Clave + "2a4A";
                } else if (E5a9Años.isSelected()) {
                    Edad = "5-9 Años";
                    Clave = Clave + "5a9A";
                } else if (E10a14Años.isSelected()) {
                    Edad = "10-14 Años";
                    Clave = Clave + "10a14A";
                } else if (E15a19Años.isSelected()) {
                    Edad = "15-19 Años";
                    Clave = Clave + "15a19A";
                } else if (E20a29Años.isSelected()) {
                    Edad = "20-29 Años";
                    Clave = Clave + "20a29A";
                } else if (E30a49Años.isSelected()) {
                    Edad = "30-49 Años";
                    Clave = Clave + "30a49";
                } else if (E50a59Años.isSelected()) {
                    Edad = "50-59 Años";
                    Clave = Clave + "50a59";
                } else if (E60YMasAños.isSelected()) {
                    Edad = "60 y más Años";
                    Clave = Clave + "60yMas";
                } else {
                    JOptionPane.showMessageDialog(null, "Seleccione el rango de Edad en el\nque se encuentre la persona");
                    ControlRB = 1;
                }
                if (ControlRB == 0) {
                    if (PrimeraVezEnElAno.isSelected()) {
                        Cobertura = "Primera vez en el año";
                    } else if (NAPrimeraVezEnElAno.isSelected()) {
                        Cobertura = "N/A";
                    } else {
                        JOptionPane.showMessageDialog(null, "Seleccione una opcion de \"Cobertura\"");
                        ControlRB = 1;
                    }
                    if (ControlRB == 0) {
                        if (PacientesReferidos.isSelected()) {
                            Referencia = "Referido";
                        } else if (PacientesContraReferidos.isSelected()) {
                            Referencia = "Contrarreferido";
                        } else if (NAReferencia.isSelected()) {
                            Referencia = "N/A";
                        } else {
                            JOptionPane.showMessageDialog(null, "Seleccione una opcion de \"Referencia\"");
                            ControlRB = 1;
                        }
                        if (ControlRB == 0) {
                            if (DHIMSS.isSelected()) {
                                DerechoHabiencia = "IMSS";
                            } else if (DHISSSTE.isSelected()) {
                                DerechoHabiencia = "ISSSTE";
                            } else if (DHSMNG.isSelected()) {
                                DerechoHabiencia = "SMNG";
                            } else if (DHOtras.isSelected()) {
                                DerechoHabiencia = "Otras";
                            } else if (NADH.isSelected()) {
                                DerechoHabiencia = "N/A";
                            } else {
                                JOptionPane.showMessageDialog(null, "Seleccione la \"Derechohabiencia\" o \"No Aplica\" en otro caso");
                                ControlRB = 1;
                            }
                            if (ControlRB == 0) {
                                if (SeguroPopular.isSelected()) {
                                    SeguroP = "Seguro Popular";
                                } else if (NASeguroPopular.isSelected()) {
                                    SeguroP = "N/A";
                                } else {
                                    JOptionPane.showMessageDialog(null, "Seleccione \"Seguro Popular\" o \"No Aplica\" en otro caso");
                                    ControlRB = 1;
                                }
                                if (ControlRB == 0) {
                                    if (Prospera.isSelected()) {
                                        Program = "Prospera";
                                    } else if (NAProspera.isSelected()) {
                                        Program = "N/A";
                                    } else {
                                        JOptionPane.showMessageDialog(null, "Seleccione \"Prospera\" o \"No Aplica\" en otro caso");
                                        ControlRB = 1;
                                    }
                                    if (ControlRB == 0) {
                                        if (VEnfermedadesTransmisibles.isSelected()) {
                                            PorProg = "Enfermedades Transmisibles";
                                        } else if (VCronicoDegenerativas.isSelected()) {
                                            PorProg = "Cronico Degenerativas";
                                        } else if (VOtrasEnfermedades.isSelected()) {
                                            PorProg = "Otras Enfermedades";
                                        } else if (VASanos.isSelected()) {
                                            PorProg = "A Sanos";
                                        } else if (VPlanificacionFamiliar.isSelected()) {
                                            PorProg = "Planificacion Familiar";
                                        } else if (VSaludBucal.isSelected()) {
                                            PorProg = "Salud Bucal";
                                        } else if (VSaludMental.isSelected()) {
                                            PorProg = "Salud Mental";
                                        } else if (NAVariable.isSelected()) {
                                            PorProg = "N/A";
                                        } else {
                                            JOptionPane.showMessageDialog(null, "Seleccione una opción de \"Por Programa\" o \"No Aplica\" en otro caso");
                                            ControlRB = 1;
                                        }
                                        if (ControlRB == 0) {
                                            Persona = new Sujeto(Sexo, Frec, Edad, Referencia, Program, SeguroP, DerechoHabiencia, PorProg, Cobertura, Clave);
                                            Consultas.Personas[Recorder.rowSelected] = Persona;
                                            Consultas.ControlEdit = 1;
                                            this.dispose();
                                            Consultas.LimpiarTabla(Recorder.TablaGnral);
                                            Consultas.GenTablaDePersonas();
                                            Consultas.Rec.setVisible(true);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.dispose();
        Consultas.LimpiarTabla(Recorder.TablaGnral);
        Consultas.GenTablaDePersonas();
        Consultas.Rec.setVisible(true);
    }//GEN-LAST:event_cancelarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int index = Recorder.rowSelected;
        String key;
        
        key = Consultas.Personas[index].getSex();
        if (key.equals("Mujer")) {
            SMujer.setSelected(true);
        } else if (key.equals("Hombre")){
                SHombre.setSelected(true);
            }
        
        key = Consultas.Personas[index].getFreq();
        if (key.equals("Primera vez")) {
            FPrimeraVez.setSelected(true);
        } else if (key.equals("Subsecuente")) {
                FSubsecuente.setSelected(true);
            } 
        
        key = Consultas.Personas[index].getAge();
        if (key.equals("< 1 Año")) {
            Em1Año.setSelected(true);
        } else if (key.equals("1 Año")) {
                E1Año.setSelected(true);
            } else if (key.equals("2-4 Años")) {
                    E2a4Años.setSelected(true);
                } else if (key.equals("5-9 Años")) {
                        E5a9Años.setSelected(true);
                    } else if (key.equals("10-14 Años")) {
                            E10a14Años.setSelected(true);
                        } else if (key.equals("15-19 Años")) {
                                E15a19Años.setSelected(true);
                            } else if (key.equals("20-29 Años")) {
                                    E20a29Años.setSelected(true);
                                } else if (key.equals("30-49 Años")) {
                                        E30a49Años.setSelected(true);
                                    } else if (key.equals("50-59 Años")) {
                                            E50a59Años.setSelected(true);
                                        } else if (key.equals("60 y más Años")) {
                                                E60YMasAños.setSelected(true);
                                            } 
        
        key = Consultas.Personas[index].getCover();
        if (key.equals("Primera vez en el año")) {
            PrimeraVezEnElAno.setSelected(true);
        } else if (key.equals("N/A")) {
                NAPrimeraVezEnElAno.setSelected(true);
            } 
        
        key = Consultas.Personas[index].getRef();
        if (key.equals("Referido")) {
            PacientesReferidos.setSelected(true);
        } else if (key.equals("Contrarreferido")) {
                PacientesContraReferidos.setSelected(true);
            } else if (key.equals("N/A")) {
                    NAReferencia.setSelected(true);
                }
        
        key = Consultas.Personas[index].getDerHab();
        if (key.equals("IMSS")) {
            DHIMSS.setSelected(true);
        } else if (key.equals("ISSSTE")) {
                DHISSSTE.setSelected(true);
            } else if (key.equals("SMNG")) {
                    DHSMNG.setSelected(true);
                } else if (key.equals("Otras")) {
                        DHOtras.setSelected(true);
                    } else if (key.equals("N/A")) {
                            NADH.setSelected(true);
                        } 
        
        key = Consultas.Personas[index].getSeguro();
        if (key.equals("Seguro Popular")) {
            SeguroPopular.setSelected(true);           
        } else if (key.equals("N/A")) {
                 NASeguroPopular.setSelected(true);
            } 
        
        key = Consultas.Personas[index].getPros();
        if (key.equals("Prospera")) {
            Prospera.setSelected(true);
        } else if (key.equals("N/A")) {
                NAProspera.setSelected(true);
            } 
        
        key = Consultas.Personas[index].getPProg();
        if (key.equals("Enfermedades Transmisibles")) {
            VEnfermedadesTransmisibles.setSelected(true);
        } else if (key.equals("Cronico Degenerativas")) {
                VCronicoDegenerativas.setSelected(true);
            } else if (key.equals("Otras Enfermedades")) {
                    VOtrasEnfermedades.setSelected(true);
                } else if (key.equals("A Sanos")) {
                        VASanos.setSelected(true);
                    } else if (key.equals("Planificacion Familiar")) {
                            VPlanificacionFamiliar.setSelected(true);
                        } else if (key.equals("Salud Bucal")) {
                                VSaludBucal.setSelected(true);
                            } else if (key.equals("Salud Mental")) {
                                    VSaludMental.setSelected(true);
                                } else if (key.equals("N/A")) {
                                        NAVariable.setSelected(true);
                                    }
    }//GEN-LAST:event_formWindowOpened

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Editor dialog = new Editor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Consulta;
    private javax.swing.JRadioButton DHIMSS;
    private javax.swing.JRadioButton DHISSSTE;
    private javax.swing.JRadioButton DHOtras;
    private javax.swing.JRadioButton DHSMNG;
    private javax.swing.JRadioButton E10a14Años;
    private javax.swing.JRadioButton E15a19Años;
    private javax.swing.JRadioButton E1Año;
    private javax.swing.JRadioButton E20a29Años;
    private javax.swing.JRadioButton E2a4Años;
    private javax.swing.JRadioButton E30a49Años;
    private javax.swing.JRadioButton E50a59Años;
    private javax.swing.JRadioButton E5a9Años;
    private javax.swing.JRadioButton E60YMasAños;
    private javax.swing.JRadioButton Em1Año;
    private javax.swing.JRadioButton FPrimeraVez;
    private javax.swing.JRadioButton FSubsecuente;
    private javax.swing.ButtonGroup GCEdad;
    private javax.swing.ButtonGroup GCFrecuencia;
    private javax.swing.ButtonGroup GCSexo;
    private javax.swing.ButtonGroup GDerechoHabiencia;
    private javax.swing.ButtonGroup GPPVariable;
    private javax.swing.ButtonGroup GPorAño;
    private javax.swing.ButtonGroup GProspera;
    private javax.swing.ButtonGroup GReferencia;
    private javax.swing.ButtonGroup GSeguroPopular;
    private javax.swing.JRadioButton NADH;
    private javax.swing.JRadioButton NAPrimeraVezEnElAno;
    private javax.swing.JRadioButton NAProspera;
    private javax.swing.JRadioButton NAReferencia;
    private javax.swing.JRadioButton NASeguroPopular;
    private javax.swing.JRadioButton NAVariable;
    private javax.swing.JRadioButton PacientesContraReferidos;
    private javax.swing.JRadioButton PacientesReferidos;
    private javax.swing.JPanel PanCobertura;
    private javax.swing.JPanel PanDerechoHabiencia;
    private javax.swing.JPanel PanEdad;
    private javax.swing.JPanel PanFrecuencia;
    private javax.swing.JPanel PanPrograma;
    private javax.swing.JPanel PanReferencia;
    private javax.swing.JPanel PanSeguroPopular;
    private javax.swing.JPanel PanSexo;
    private javax.swing.JPanel PanVariable;
    private javax.swing.JRadioButton PrimeraVezEnElAno;
    private javax.swing.JRadioButton Prospera;
    private javax.swing.JRadioButton SHombre;
    private javax.swing.JRadioButton SMujer;
    private javax.swing.JRadioButton SeguroPopular;
    private javax.swing.JRadioButton VASanos;
    private javax.swing.JRadioButton VCronicoDegenerativas;
    private javax.swing.JRadioButton VEnfermedadesTransmisibles;
    private javax.swing.JRadioButton VOtrasEnfermedades;
    private javax.swing.JRadioButton VPlanificacionFamiliar;
    private javax.swing.JRadioButton VSaludBucal;
    private javax.swing.JRadioButton VSaludMental;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton guardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables

    public void LimpiarControles() {
            ControlRB = 0;
            ControlSexo = 0;
            ControlFreq = 0;
            ControlProg = 0;
        }
}
